# safelist (TravisCI will only build pushes to branches in this list)
branches:
  only:
  - master

language: python
python: 3.6
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
install: "pip install Lektor"
script: "lektor build"
deploy:
  provider: script
  # Note that the credentials are supplied securely (password should be a
  # personal token). See https://www.getlektor.com/docs/deployment/travisci/
  #   $ export LEKTOR_DEPLOY_USERNAME=[secure]
  #   $ export LEKTOR_DEPLOY_PASSWORD=[secure]
  script: "lektor deploy ghpages"
  on:
    branch: master
