# safelist (TravisCI will only build pushes to branches in this list)
branches:
  only:
  - master

language: python
python: 3.6
install: "pip install Lektor"
script: "lektor build"
deploy:
  provider: script
  github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  script: "lektor deploy ghpages"
  on:
    branch: master