name: Website pa11y tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check-a11y:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Install node 
      uses: actions/setup-node@v1
      with:
        node-version: "12.x"

    - name: Install pa11y
      run: npm ci
    
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-s
    
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7' # Match the runtime version in CloudFare
    
    - name: Install dependencies
      run: python -m pip install -r requirements.txt

    - name: Check site a11y
      run: |
        nikola auto & sleep 10
        npm run test-pally | tee pa11y_output.txt
        kill $(cat nikolaserve.pid)

    - name: Read pa11y_output file.
      id: pa11y_output
      uses: juliangruber/read-file-action@v1
      with:
        path: ./pa11y_output.txt
        
    - name: 'Comment PR'
      uses: actions/github-script@v4
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## Pa11y testing results 
              
              ```{{ steps.pa11y_output.outputs.content }}```'
            })